### ISSUE TITLE
Compile error

### ISSUE THREAD

**Issue by nguyenbaodanh** [ismail0234/BB-CS-GO-Custom-Weapons#1]
//// weapon_crossbow.sp
//
// weapon_crossbow.sp(152) : error 017: undefined symbol "RemoveEntityById"
//
// 1 Error.
//
// Compilation Time: 0.12 sec
// ----------------------------------------

**Comment by ismail0234** [comment]
@nguyenbaodanh because this is in the alpha version. The current code here is just the design code. Alpha codes have not been released yet.
