### ISSUE TITLE
No plugin for the natives

### ISSUE THREAD

**Issue by eyal282** [ismail0234/BB-CS-GO-Custom-Weapons#2]
I see there isn't a plugin for the natives provided. I intend to use this as an optional dependency on my Ultimate JailBreak Package's LR plugin. Instead of explosive bows ( 0 skill involved ) the arrows will make you bleed ( like Karma's TTT Crossbow item for T )

Tried adding you, it said you aren't accepting invites. This is my discord if you wanna discuss that there:
Eyal282#1334

**Comment by ismail0234** [comment]
Hello,

 This is an incomplete plugin. I don't develop plugins in csgo anymore.
